title: Julia Donato # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Science professional pursuing a master's degree in data science at Indiana University Bloomington, with a focus on data analysis, machine learning, and predictive modeling
  <br><br>
  My goal is to make a meaningful impact in the world of data science and contribute to the success of organizations through the application of data-driven solutions. 
  <br><br>
  <a href="https://www.linkedin.com/in/julia-donato-92ba3b167/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="github.com/julia-donato">View My GitHub Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

