title: Julia Donato
# your name (or website title) here
logo: "/images/logo.png?raw=true" 
# your photo (or logo) here
description: >
  I am an aspiring data professional with a Master's degree in Data Science from Indiana University Bloomington, where I achieved a notable 3.94 GPA. My expertise lies in data analysis, data engineering, and predictive modeling, offering a solid foundation to address and unravel complex data-centric problems effectively.
  <br><br>
  My goal is to make a meaningful impact in the world of data science/analytics and contribute to the success of organizations through the application of data-driven solutions. 
  <br><br>
  <a href="https://www.linkedin.com/in/julia-donato-92ba3b167/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="github.com/julia-donato">View My GitHub Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
